const membersData = [
    {
        "id": "안종혁",
        "name": "안종혁",
        "constituency": "천안3",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1973.1.28.",
        "address": "천안시 동남구 청수14로",
        "education": "성균관대학교 대학원",
        "career": "(전)천안시의회의원",
        "region": "천안시 제3선거구 문정동, 봉명동, 성정1동, 성정2동",
        "committee1": "기획경제위원회",
        "committee2": "기획경제위원회\n위원장",
        "plenary_5min": "[352회] 조치원호와 온양호를 통해 일깨우는 호국보훈 정신\n[350회] 의사가 쓰는 칼은 생명을 지키는 칼입니다(2024. 3. 5.)\n[349회] 충청남도 공공기관 공동이용시설 구축 제안(2024. 1. 23.)",
        "plenary_question": "[345회] 통상사무소 사업확장 및 거점 역할\n[345회] 장애인 일자리지원 안내 추진\n[345회] 천안시 하천변 편익시설 마련\n[345회] 다양한 가족 구성원에 대한 교직자 교육 필요",
        "plenary_bill": "[358회] 충청남도 외국인유치센터 설치 및 운영에 관한 조례 전부개정조례안\n[355회] 충청남도 프랜차이즈산업 육성 및 지원에 관한 조례안\n[355회] 충청남도공무원 후생복지제도 운영에 관한 조례 일부개정조례안\n[351회] 충청남도 지역종합유선방송 발전 지원에 관한 조례안\n[350회] 충청남도 금융복지 지원에 관한 조례안\n[349회] 제조업 인력난 해소를 위한 외국인노동자 비자 확대 촉구 건의안\n[345회] 충청남도 외국인유치센터 설치 및 운영에 관한 조례안\n[340회] 충청남도 베이밸리 메가시티 건설 민‧관 합동 추진단 구성 및 운영에 관한 조례안",
        "plenary_suggestion": "[355회] 대전출입국관리사무소 천안출장소, 충남 출입국·외국인사무소 승격 촉구 건의안",
        "plenary_research": "[의정 토론회] 하천 산책로 화장실 설치 등 편익 시설 마련 (2022. 11. 3.)\n[연구모임] (2023) 충남 프랜차이즈 산업 육성 및 지원\n[연구모임] (2024) 충남 프랜차이즈 산업 육성 및 지원",
        "standing_coms": [],
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "구형서",
        "name": "구형서",
        "constituency": "천안4",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1981.11.26.",
        "address": "천안시 서북구 불당 21로",
        "education": "단국대학교",
        "career": "(전)더불어민주당 중앙당 부대변인",
        "region": "불당1동, 불당2동",
        "committee1": "교육위원회(부위원장), 운영위원회",
        "committee2": "기획경제위원회(부위원장)",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "이종화",
        "name": "이종화",
        "constituency": "홍성2",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1960.4.28.",
        "address": "홍성군 광천읍 광천로",
        "education": "충남대학교 대학원",
        "career": "(전)홍성군의회의원",
        "region": "광천읍, 금마면, 홍동면, 장곡면, 은하면, 결성면, 서부면, 갈산면, 구항면",
        "committee1": "기획경제위원회",
        "committee2": "기획경제위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "안장헌",
        "name": "안장헌",
        "constituency": "아산5",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1976.8.5.",
        "address": "아산시 배방읍 호서로",
        "education": "성균관대학교",
        "career": "(전)아산시의회의원",
        "region": "배방읍, 송악면",
        "committee1": "행정문화위원회",
        "committee2": "기획경제위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "이정우",
        "name": "이정우",
        "constituency": "청양",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1959.12.6.",
        "address": "청양군 청양읍 중앙로",
        "education": "호원대학교",
        "career": "충청남도의회의원",
        "region": "청양군 전 읍면",
        "committee1": "기획경제위원회",
        "committee2": "기획경제위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "activities_debate": "",
        "audit_coms": []
    },
    {
        "id": "김도훈",
        "name": "김도훈",
        "constituency": "천안6",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1976.1.7.",
        "address": "천안시 서북구 시청로",
        "education": "단국대학교",
        "career": "(전)충청남도 축구협회 이사",
        "region": "성거읍, 부성1동",
        "committee1": "건설소방위원회, 예산결산특별위원회",
        "committee2": "기획경제위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "박정식",
        "name": "박정식",
        "constituency": "아산3",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1974.10.30.",
        "address": "아산시 순천향로",
        "education": "고구려대학",
        "career": "국민의힘 충남도당 대변인",
        "region": "온양5동, 온양6동",
        "committee1": "교육위원회, 예산결산특별위원회",
        "committee2": "기획경제위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "지민규",
        "name": "지민규",
        "constituency": "아산6",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1993.4.16.",
        "address": "아산시 음봉면 음봉로",
        "education": "고려대학교 대학원",
        "career": "충청남도 청년네트워크위원장",
        "region": "음봉면, 둔포면, 영인면, 인주면",
        "committee1": "복지환경위원회",
        "committee2": "기획경제위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "이현숙",
        "name": "이현숙",
        "constituency": "비례",
        "party": "국민의힘",
        "gender": "여",
        "birthDate": "1966.5.1.",
        "address": "천안시 서북구 충무로",
        "education": "창덕여자고등학교",
        "career": "주민자치전국여성회장",
        "region": "비례대표",
        "committee1": "행정문화위원회",
        "committee2": "행정문화위원회(부위원장)",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "오인철",
        "name": "오인철",
        "constituency": "천안7",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1967.5.24.",
        "address": "천안시 서북구 두정중2길",
        "education": "강남대학교 대학원",
        "career": "강남대학교 겸임교수",
        "region": "부성2동",
        "committee1": "농수산해양위원회, 운영위원회",
        "committee2": "제2부의장, 행정문화위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "김옥수",
        "name": "김옥수",
        "constituency": "서산1",
        "party": "국민의힘",
        "gender": "여",
        "birthDate": "1959.7.28.",
        "address": "서산시 인지면 둔당로",
        "education": "삼성여자고등학교",
        "career": "충청남도 새마을부녀회 회장",
        "region": "대산읍, 인지면, 부석면, 팔봉면, 지곡면",
        "committee1": "행정문화위원회(위원장)",
        "committee2": "행정문화위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "전익현",
        "name": "전익현",
        "constituency": "서천1",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1961.3.8.",
        "address": "서천군 마서면 장서로 578번길",
        "education": "군산대학교 대학원",
        "career": "서천군의회 의원",
        "region": "장항읍, 마서면, 화양면, 기산면, 한산면, 마산면",
        "committee1": "교육위원회, 예산결산특별위원회",
        "committee2": "행정문화위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "윤기형",
        "name": "윤기형",
        "constituency": "논산1",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1962.1.30.",
        "address": "논산시 연무읍 안심로 61번길",
        "education": "건양대학교 대학원",
        "career": "국민의힘 충남도당 부위원장",
        "region": "강경읍, 연무읍, 연산면, 벌곡면, 양촌면, 은진면, 가야곡면, 채운면",
        "committee1": "기획경제위원회(부위원장)",
        "committee2": "행정문화위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "주진하",
        "name": "주진하",
        "constituency": "예산2",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1964.10.1.",
        "address": "예산군 삽교읍 두리2길",
        "education": "공주대학교 대학원",
        "career": "농협중앙해 예산군지부장",
        "region": "삽교읍, 대흥면, 응봉면, 덕산면, 봉산면, 고덕면, 신암면, 오가면",
        "committee1": "농수산해양위원회",
        "committee2": "행정문화위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "최광희",
        "name": "최광희",
        "constituency": "보령1",
        "party": "무소속",
        "gender": "남",
        "birthDate": "1965.3.5.",
        "address": "보령시 동현로",
        "education": "한밭대학교",
        "career": "(전)보령시 안전행정국장",
        "region": "웅천읍,남포면,주산면,미산면,성주면,대천3동,대천4동, 대천5동",
        "committee1": "행정문화위원회",
        "committee2": "행정문화위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "김민수",
        "name": "김민수",
        "constituency": "비례",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1972.8.24.",
        "address": "부여군 부여읍 백마강길",
        "education": "공주대학교 대학원",
        "career": "부여군의회 의원",
        "region": "비례대표",
        "committee1": "농수산해양위원회",
        "committee2": "보건복지환경위원회(위원장)",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "신순옥",
        "name": "신순옥",
        "constituency": "비례",
        "party": "국민의힘",
        "gender": "여",
        "birthDate": "1977.8.15.",
        "address": "천안시 서북구 불당24로",
        "education": "이화여자대학교 대학원",
        "career": "백석예술대 외래교수",
        "region": "비례대표",
        "committee1": "교육위원회",
        "committee2": "보건복지환경위원회(부위원장)",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "김석곤",
        "name": "김석곤",
        "constituency": "금산1",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1952.4.25.",
        "address": "금산군 금산읍 비단로",
        "education": "중앙대학교",
        "career": "충청남도의회 의원",
        "region": "부리면, 남일면, 남이면",
        "committee1": "기획경제위원회",
        "committee2": "보건복지환경위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "정광섭",
        "name": "정광섭",
        "constituency": "태안2",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1959.10.20.",
        "address": "태안군 안면읍 응지마을길",
        "education": "충남도립대학교",
        "career": "충청남도의회 의원",
        "region": "안면읍, 고남면, 남면, 근흥면, 소원면",
        "committee1": "농수산해양위원회(위원장)",
        "committee2": "제1부의장, 보건복지환경위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "activities_debate": "",
        "audit_coms": []
    },
    {
        "id": "박정수",
        "name": "박정수",
        "constituency": "천안9",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1976.1.14.",
        "address": "천아시 동남구 광덕면 자무실길",
        "education": "성균관대학교",
        "career": "(전)국민의당 충남도당 청년위원장",
        "region": "풍세면, 광덕면, 신방동",
        "committee1": "행정문화위원회",
        "committee2": "보건복지환경위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "이철수",
        "name": "이철수",
        "constituency": "당진1",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1960.9.5.",
        "address": "당진시 당진시장길",
        "education": "한경대학교 대학원",
        "career": "당진시의회 의원",
        "region": "합덕읍, 대호지면, 정미면, 면천면, 순성면, 우강면, 당진2동",
        "committee1": "복지환경위원회",
        "committee2": "보건복지환경위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "정병인",
        "name": "정병인",
        "constituency": "천안8",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1972.6.24.",
        "address": "천안시 서북구 한들3로",
        "education": "충남대학교 대학원",
        "career": "천안시의회 의원",
        "region": "백석동",
        "committee1": "복지환경위원회",
        "committee2": "보건복지환경위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "이연희",
        "name": "이연희",
        "constituency": "서산3",
        "party": "국민의힘",
        "gender": "여",
        "birthDate": "1969.9.28.",
        "address": "서산시 예천5로",
        "education": "충남대학교 대학원",
        "career": "서산시의회의장",
        "region": "음암면, 운산면, 해미읍, 고북면, 동문1.2동, 수석동",
        "committee1": "복지환경위원회, 예산결산특별위원회",
        "committee2": "농수산해양위원회(위원장)",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "신영호",
        "name": "신영호",
        "constituency": "서천2",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1981.6.8.",
        "address": "서천군 서천읍",
        "education": "연세대학교 행정대학원",
        "career": "세종대학교 다문화연구소 정책연구원",
        "region": "서천읍, 시초면, 문산면, 판교면, 종천면, 비인면, 서면",
        "committee1": "농수산해양위원회",
        "committee2": "농수산해양위원회(부위원장)",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "조길연",
        "name": "조길연",
        "constituency": "부여2",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1951.9.6.",
        "address": "부여군 장암면 상하로",
        "education": "인천체육전문학교",
        "career": "충청남도의회 의원",
        "region": "은산면, 외산면, 내산면, 구룡면, 홍산면, 옥산면, 남면, 충화면, 양화면, 임천면, 장암면, 세도면, 석성면, 초촌면",
        "committee1": "의장",
        "committee2": "농수산해양위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "activities_debate": "",
        "audit_coms": []
    },
    {
        "id": "김복만",
        "name": "김복만",
        "constituency": "금산2",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1946.2.13.",
        "address": "금산군 군북면 새말길",
        "education": "금산고등공민학교",
        "career": "충청남도의회 의원",
        "region": "금성면, 제원면, 군북면, 진산면, 북수면, 추부면",
        "committee1": "농수산해양위원회",
        "committee2": "농수산해양위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "오인환",
        "name": "오인환",
        "constituency": "논산2",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1968.7.18.",
        "address": "논산시 체육로",
        "education": "충남대학교 대학원",
        "career": "충청남도의회 의원",
        "region": "성동면, 광석면, 노성면, 상월면, 부적면, 취암동, 부창동",
        "committee1": "행정문화위원회",
        "committee2": "농수산해양위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "오안영",
        "name": "오안영",
        "constituency": "아산1",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1965.3.15.",
        "address": "아산시 선장면 삼봉산길",
        "education": "아산고등학교",
        "career": "아산시의회 의장",
        "region": "선장면, 도고면, 신창면, 온양4동",
        "committee1": "농수산해양위원회",
        "committee2": "농수산해양위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "편삼범",
        "name": "편삼범",
        "constituency": "보령2",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1959.9.19.",
        "address": "보령시 오천면 장고도1길",
        "education": "충남도립대학교",
        "career": "보령시의회 의원",
        "region": "주포면,오천면,천북면,청소면,청라면,주교면,대천1동,대천2동",
        "committee1": "교육위원회(위원장)",
        "committee2": "농수산해양위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "activities_debate": "",
        "audit_coms": []
    },
    {
        "id": "고광철",
        "name": "고광철",
        "constituency": "공주1",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1958.7.24.",
        "address": "공주시 공주대학로",
        "education": "공주대학교 대학원",
        "career": "공주시의회 의장",
        "region": "유구읍,의당면,정안면,우성면, 사곡면,신풍면,신관동,월송동",
        "committee1": "건설소방위원회",
        "committee2": "건설소방위원회(위원장)",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "홍기후",
        "name": "홍기후",
        "constituency": "당진3",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1974.2.24.",
        "address": "당진시 밤절로104",
        "education": "연세대학교 공학대학원",
        "career": "충청남도의회 의원",
        "region": "고대면,석문면,당진1동·3동",
        "committee1": "건설소방위원회",
        "committee2": "건설소방위원회(부위원장)",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "activities_debate": "",
        "audit_coms": []
    },
    {
        "id": "박미옥",
        "name": "박미옥",
        "constituency": "비례",
        "party": "국민의힘",
        "gender": "여",
        "birthDate": "1965.5.20.",
        "address": "공주시 반포면 금벽로",
        "education": "공주대학교 대학원",
        "career": "(현)국민의힘 충남도당 여성위원장",
        "region": "비례대표",
        "committee1": "교육위원회",
        "committee2": "농수산해양위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "김기서",
        "name": "김기서",
        "constituency": "부여1",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1973.4.26.",
        "address": "부여군 부여읍 서동로",
        "education": "고려대학교 대학원",
        "career": "충청남도의회 의원",
        "region": "부여읍, 규암면",
        "committee1": "건설소방위원회",
        "committee2": "건설소방위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "조철기",
        "name": "조철기",
        "constituency": "아산4",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1965.9.23.",
        "address": "아산시 탕정면 탕정면로",
        "education": "예산농업전문대학교",
        "career": "충청남도의회 의원",
        "region": "배방읍 세교리·장재리·휴대리, 탕정면, 염치읍",
        "committee1": "건설소방위원회",
        "committee2": "건설소방위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "양경모",
        "name": "양경모",
        "constituency": "천안11",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1961.2.1.",
        "address": "천안시 서북구 쌍용18길",
        "education": "예산농업전문대학교",
        "career": "국민의힘 충남도당 부위원장",
        "region": "쌍용1·2·3동",
        "committee1": "복지환경위원회",
        "committee2": "건설소방위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "윤희신",
        "name": "윤희신",
        "constituency": "태안1",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1968.12.23.",
        "address": "태안군 태안읍 샘골로",
        "education": "아주대학교",
        "career": "태안군사회복지협의회장",
        "region": "태안읍, 원북면, 이원면",
        "committee1": "교육위원회",
        "committee2": "건설소방위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "이재운",
        "name": "이재운",
        "constituency": "계룡시",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1965.3.20.",
        "address": "계룡시 두마면 왕대1길",
        "education": "대전대학교 대학원",
        "career": "계룡시의회 의장",
        "region": "계룡시",
        "committee1": "기획경제위원회",
        "committee2": "건설소방위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "이해선",
        "name": "이해선",
        "constituency": "당진2",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1965.",
        "address": "당진시 당진1동",
        "education": "동국대학교 경찰행정학과",
        "career": "당진시청 경제환경국장",
        "region": "송악, 신평, 송산",
        "committee1": "해당없음",
        "committee2": "건설소방위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "activities_debate": "",
        "audit_coms": []
    },
    {
        "id": "이상근",
        "name": "이상근",
        "constituency": "홍성1",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1961.1.15.",
        "address": "홍성군 홍성읍 문화로 85번길",
        "education": "고려대학교 대학원",
        "career": "홍성군의회 의장",
        "region": "홍성읍, 홍북읍",
        "committee1": "행정문화위원회(부위원장)",
        "committee2": "교육위원회(위원장)",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "이용국",
        "name": "이용국",
        "constituency": "서산2",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1981.8.31.",
        "address": "서산시 예천5로",
        "education": "지곡고등학교",
        "career": "(현)국민의힘 충남도당 부위원장",
        "region": "성연면, 부촌동, 석남동",
        "committee1": "건설소방위원회",
        "committee2": "교육위원회(부위원장)",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "김응규",
        "name": "김응규",
        "constituency": "아산2",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1955.7.29.",
        "address": "아산시 문화로 243번길",
        "education": "단국대학교 대학원",
        "career": "아산시의회 의장",
        "region": "온양1.2.3동",
        "committee1": "복지환경위원회(위원장)",
        "committee2": "교육위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "방한일",
        "name": "방한일",
        "constituency": "예산1",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1958.4.21.",
        "address": "예산읍 아리랑로",
        "education": "공주대학교 대학원",
        "career": "충청남도의회 의원",
        "region": "예산읍,대술면,신양면,광시면",
        "committee1": "복지환경위원회",
        "committee2": "교육위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "김선태",
        "name": "김선태",
        "constituency": "천안10",
        "party": "더불어민주당",
        "gender": "남",
        "birthDate": "1970.4.20.",
        "address": "천안시 동남구 구성11길",
        "education": "경희대학교 대학원",
        "career": "천안시의회 의원",
        "region": "청룡동",
        "committee1": "복지환경위원회",
        "committee2": "교육위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "신한철",
        "name": "신한철",
        "constituency": "천안2",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1979.5.20.",
        "address": "천안시 동남구 신부8길",
        "education": "한국기술교육대학",
        "career": "(현)국민의힘 충남도당 부대변인",
        "region": "중앙동,일봉동,신안동",
        "committee1": "건설소방위원회",
        "committee2": "교육위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "유성재",
        "name": "유성재",
        "constituency": "천안5",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1960.10.15.",
        "address": "천안시 서북구 입장면 반월길",
        "education": "한국교육대학교 대학원",
        "career": "(전)천안중앙고 교사",
        "region": "성환읍, 직산읍",
        "committee1": "농수산해양위원회",
        "committee2": "교육위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "이지윤",
        "name": "이지윤",
        "constituency": "비례",
        "party": "더불어민주당",
        "gender": "여",
        "birthDate": "1989.3.10.",
        "address": "아산시 탕정면 매곡중앙3로",
        "education": "성신여자대학교",
        "career": "(현)더불어민주당 충남도당 상근대변인",
        "region": "비례대표",
        "committee1": "기획경제위원회(위원장)",
        "committee2": "교육위원회",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    },
    {
        "id": "박기영",
        "name": "박기영",
        "constituency": "공주1",
        "party": "국민의힘",
        "gender": "남",
        "birthDate": "1957.6.7.",
        "address": "공주시 웅진로",
        "education": "공주대학교 대학원",
        "career": "(전)공주시의회 부의장",
        "region": "이인면,탄천면,계룡면,반포면,중학동,웅진동,금학동,옥룡동",
        "committee1": "행정문화위원회",
        "committee2": "행정문화위원회(위원장)",
        "activities_5min": "",
        "activities_question": "",
        "activities_bill": "",
        "activities_suggestion": "",
        "activities_research": "",
        "standing_coms": [],
        "audit_coms": [],
        "activities_debate": ""
    }
];